### ISSUE TITLE
Support SGD format /SG\$\d+/ format

### ISSUE THREAD

**Issue by kjones1876** [bodar/totallylazy.js#16]
IRL example:  https://www.expedia.com.sg/Singapore-Hotels-Hotel-Boss.h13307850.Hotel-Information?chkin=2021-02-11&chkout=2021-02-12&currency=SGD&rm1=a2

```
it('can handle SG$ SGD format', () => {
    assert.deepEqual(flexibleParse('SG$328', 'en-SG'), money('SGD', 328));
    assert.deepEqual(flexibleParse('SG$328'), money('SGD', 328));
});
```

**Comment by danielbodart** [comment]
This was fixed in 86c9bd6bb29a598bfccc41746caf847815a10ab5
