### ISSUE TITLE
Israeli New Shekel not supported

### ISSUE THREAD

**Issue by asiaellis5** [bodar/totallylazy.js#20]
We tried to decode the money parser using the Israeli New Shekel symbol and it doesn't recognise it. Is this something you could support?

```
assert.deepEqual(flexibleMoneyParser('iw').parseAll('‏‏595 ₪'), [money('ILS', 595)])
AssertionError: expected [] to deeply equal [ { amount: 595, currency: 'ILS' } ]
      + expected - actual

      -[]
      +[
      +  {
      +    "amount": 595
      +    "currency": "ILS"
      +  }
      +]
```

**Comment by danielbodart** [comment]
This is actually nothing to do with Israeli New Shekel, your input contained a RTL unicode marker (You probably didn't notice as you use VSCode which doesn't show you them).
