### ISSUE TITLE
zambia kwacha not supported

### ISSUE THREAD

**Issue by kjones1876** [bodar/totallylazy.js#21]
flexibleMoneyParser cant read Zambian Kwacha. This is the price and locale as present by google hotel ads.

```
assert.deepEqual(flexibleMoneyParser('en-ZM').parseAll('‏‏K 2,976'), [money('ZMW', 2976)])
```

**Comment by danielbodart** [comment]
I've pushed a change that allows this to work without any additional config. Previously you would have had to do something like this:
```
flexibleMoneyParser('en-ZM', {strategy: infer('en-ZM')})
```

**Comment by danielbodart** [comment]
But is seemed a bit superfluous, I tend to prefer explicit APIs and not magic ones but in this instance it feels safe enough. But we will see...
